const allergyOptions = [
  { value: "egg", label: "계란" },
  { value: "dairy", label: "유제품" },
  { value: "wheat", label: "밀/글루텐" },
  { value: "peanut", label: "땅콩" },
  { value: "soy", label: "대두" },
  { value: "seafood", label: "해산물" },
  { value: "shellfish", label: "갑각류" },
  { value: "pork", label: "돼지고기" }
];

const goalProfiles = {
  diet: {
    label: "체지방 감량",
    calorieDelta: -450,
    macroRatio: { carb: 0.35, protein: 0.35, fat: 0.3 },
    tips: ["매 끼니 단백질 우선", "가공식품·액상당류 최소화", "저녁 지방 섭취 조절"]
  },
  muscle: {
    label: "근육 증가",
    calorieDelta: 280,
    macroRatio: { carb: 0.42, protein: 0.33, fat: 0.25 },
    tips: ["운동 전후 탄단 섭취", "하루 수분 2L 이상", "동일 단백질군 과반복 방지"]
  },
  liver: {
    label: "간 건강",
    calorieDelta: -120,
    macroRatio: { carb: 0.43, protein: 0.32, fat: 0.25 },
    tips: ["저염 조리 우선", "튀김·가공육 빈도 축소", "국물류 나트륨 확인"]
  },
  study: {
    label: "집중력 강화",
    calorieDelta: 0,
    macroRatio: { carb: 0.4, protein: 0.3, fat: 0.3 },
    tips: ["혈당 급등 식사 피하기", "점심 과식 방지", "오메가3 식품 주기적 섭취"]
  },
  general: {
    label: "균형 건강",
    calorieDelta: 0,
    macroRatio: { carb: 0.45, protein: 0.3, fat: 0.25 },
    tips: ["통곡물 비중 확대", "단백질원 다양화", "주간 식단 균형 점검"]
  }
};

const situationGuides = {
  office: "사무직은 점심 과식과 나른함을 줄이기 위해 탄수화물 양과 단백질 비율을 조절하세요.",
  busy: "바쁜 일정은 20분 내 조리 가능한 메뉴 비율을 높이고, 주 2회 선조리를 권장합니다.",
  student: "학습 집중이 필요할 때는 통곡물+단백질+건강한 지방 조합을 유지하세요.",
  workout: "운동일은 단백질 섭취량과 운동 전후 탄수화물 타이밍을 함께 맞추세요.",
  night: "야근일은 늦은 시간 고지방 식사를 피하고 나트륨과 총열량을 낮춘 메뉴를 선택하세요."
};

const recipeCatalog = [
  {
    id: "b01",
    title: "그릭요거트 베리볼",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    goals: ["diet", "study", "general"],
    situations: ["office", "student", "busy"],
    proteinGroup: "dairy",
    prepTime: 8,
    nutrition: { calories: 340, protein: 23, carbs: 41, fat: 9, sodium: 120 },
    ingredients: ["그릭요거트 170g", "블루베리 70g", "오트 35g", "호두 10g"],
    steps: ["볼에 요거트와 오트를 담습니다.", "베리와 호두를 올려 마무리합니다."],
    tip: "단맛이 필요하면 바나나 1/3개를 추가하세요."
  },
  {
    id: "b02",
    title: "오버나이트 오트밀",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    goals: ["diet", "study", "general"],
    situations: ["busy", "office"],
    proteinGroup: "plant",
    prepTime: 6,
    nutrition: { calories: 360, protein: 19, carbs: 49, fat: 10, sodium: 130 },
    ingredients: ["오트밀 50g", "우유 또는 두유 180ml", "치아시드", "사과"],
    steps: ["전날 밤 용기에 재료를 섞어 냉장 보관합니다.", "아침에 과일을 얹어 섭취합니다."],
    tip: "바쁜 아침에 가장 안정적인 식사입니다."
  },
  {
    id: "b03",
    title: "시금치 버섯 오믈렛",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: ["egg"],
    goals: ["muscle", "general", "study"],
    situations: ["office", "workout"],
    proteinGroup: "egg",
    prepTime: 12,
    nutrition: { calories: 330, protein: 26, carbs: 12, fat: 20, sodium: 340 },
    ingredients: ["달걀 2개", "시금치", "양송이", "올리브오일"],
    steps: ["팬에 버섯과 시금치를 볶습니다.", "풀어둔 달걀을 부어 접어 익힙니다."],
    tip: "탄수화물이 필요하면 통밀빵 반 장을 곁들이세요."
  },
  {
    id: "b04",
    title: "훈제연어 아보카도 토스트",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["pescatarian"],
    allergens: ["wheat", "seafood"],
    goals: ["study", "general", "muscle"],
    situations: ["student", "workout"],
    proteinGroup: "seafood",
    prepTime: 10,
    nutrition: { calories: 430, protein: 24, carbs: 34, fat: 23, sodium: 520 },
    ingredients: ["통밀빵 1장", "훈제연어 70g", "아보카도 1/2개", "레몬즙"],
    steps: ["빵을 굽고 아보카도를 으깨 바릅니다.", "연어를 올리고 레몬즙으로 마무리합니다."],
    tip: "나트륨이 걱정되면 연어 양을 줄여 조절하세요."
  },
  {
    id: "b05",
    title: "두부 스크램블 랩",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["wheat", "soy"],
    goals: ["diet", "liver", "general"],
    situations: ["busy", "office"],
    proteinGroup: "plant",
    prepTime: 13,
    nutrition: { calories: 390, protein: 22, carbs: 38, fat: 15, sodium: 380 },
    ingredients: ["통밀 또띠아", "두부 140g", "양파", "파프리카"],
    steps: ["두부와 채소를 스크램블 형태로 볶습니다.", "또띠아에 넣고 말아 완성합니다."],
    tip: "달걀 알레르기 대체 아침으로 적합합니다."
  },
  {
    id: "b06",
    title: "닭가슴살 현미주먹밥",
    mealType: "breakfast",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["soy"],
    goals: ["muscle", "general"],
    situations: ["busy", "workout"],
    proteinGroup: "chicken",
    prepTime: 15,
    nutrition: { calories: 430, protein: 31, carbs: 50, fat: 9, sodium: 420 },
    ingredients: ["현미밥 180g", "닭가슴살 100g", "김가루", "저염간장"],
    steps: ["닭가슴살을 삶아 찢습니다.", "현미밥과 섞어 주먹밥으로 만듭니다."],
    tip: "한 개는 오전 간식으로 활용 가능합니다."
  },
  {
    id: "b07",
    title: "바나나 단백질 스무디볼",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    goals: ["muscle", "general"],
    situations: ["workout", "busy"],
    proteinGroup: "dairy",
    prepTime: 7,
    nutrition: { calories: 420, protein: 30, carbs: 47, fat: 10, sodium: 190 },
    ingredients: ["바나나", "우유 200ml", "단백질파우더", "오트"],
    steps: ["모든 재료를 블렌더에 갈아 볼에 담습니다.", "기호에 따라 과일 토핑을 올립니다."],
    tip: "운동 직후 아침으로 적합합니다."
  },
  {
    id: "b08",
    title: "북어두부국과 밥",
    mealType: "breakfast",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["seafood", "soy"],
    goals: ["liver", "general"],
    situations: ["night", "office"],
    proteinGroup: "plant",
    prepTime: 18,
    nutrition: { calories: 370, protein: 24, carbs: 45, fat: 9, sodium: 510 },
    ingredients: ["북어채", "두부", "무", "현미밥"],
    steps: ["북어채를 볶고 물을 부어 끓입니다.", "두부와 무를 넣고 간을 약하게 맞춥니다."],
    tip: "저염으로 조리하면 간 건강 관리에 좋습니다."
  },
  {
    id: "b09",
    title: "병아리콩 후무스 샌드",
    mealType: "breakfast",
    cuisine: "mediterranean",
    dietary: ["vegetarian"],
    allergens: ["wheat"],
    goals: ["diet", "study", "general"],
    situations: ["busy", "student"],
    proteinGroup: "plant",
    prepTime: 11,
    nutrition: { calories: 385, protein: 17, carbs: 49, fat: 13, sodium: 340 },
    ingredients: ["통밀빵", "후무스", "토마토", "오이", "루꼴라"],
    steps: ["빵에 후무스를 바릅니다.", "채소를 넣어 샌드위치를 완성합니다."],
    tip: "채식 아침으로 포만감이 좋습니다."
  },
  {
    id: "b10",
    title: "코티지치즈 과일볼",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    goals: ["diet", "general", "study"],
    situations: ["office", "student"],
    proteinGroup: "dairy",
    prepTime: 6,
    nutrition: { calories: 315, protein: 24, carbs: 28, fat: 10, sodium: 280 },
    ingredients: ["코티지치즈", "키위", "딸기", "아몬드"],
    steps: ["볼에 코티지치즈를 담습니다.", "과일과 견과류를 올려 마무리합니다."],
    tip: "당류가 낮은 과일을 우선 선택하세요."
  },
  {
    id: "b11",
    title: "참치달걀 통밀샌드",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: ["egg", "wheat", "seafood"],
    goals: ["muscle", "general"],
    situations: ["busy", "workout"],
    proteinGroup: "seafood",
    prepTime: 12,
    nutrition: { calories: 445, protein: 31, carbs: 36, fat: 18, sodium: 560 },
    ingredients: ["통밀식빵", "참치", "삶은 달걀", "요거트 소스"],
    steps: ["참치와 달걀을 으깨 소스를 섞습니다.", "빵 사이에 채워 샌드위치를 만듭니다."],
    tip: "운동일 고단백 아침에 유리합니다."
  },
  {
    id: "b12",
    title: "오트바나나 팬케이크",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["egg"],
    goals: ["study", "general"],
    situations: ["student", "office"],
    proteinGroup: "egg",
    prepTime: 16,
    nutrition: { calories: 390, protein: 18, carbs: 55, fat: 11, sodium: 210 },
    ingredients: ["오트가루", "바나나", "달걀", "우유"],
    steps: ["재료를 섞어 반죽을 만듭니다.", "팬에 한 장씩 구워 완성합니다."],
    tip: "시럽 대신 과일로 단맛을 보충하세요."
  },
  {
    id: "b13",
    title: "퀴노아 견과 죽",
    mealType: "breakfast",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: [],
    goals: ["diet", "general", "liver"],
    situations: ["office", "night"],
    proteinGroup: "plant",
    prepTime: 20,
    nutrition: { calories: 360, protein: 15, carbs: 52, fat: 10, sodium: 180 },
    ingredients: ["퀴노아", "귀리", "호두", "사과", "계피"],
    steps: ["퀴노아와 귀리를 함께 끓입니다.", "과일과 견과류를 넣어 마무리합니다."],
    tip: "소화가 예민한 날 따뜻하게 섭취하세요."
  },
  {
    id: "b14",
    title: "닭고기 야채죽",
    mealType: "breakfast",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: [],
    goals: ["liver", "general", "study"],
    situations: ["night", "busy"],
    proteinGroup: "chicken",
    prepTime: 22,
    nutrition: { calories: 400, protein: 25, carbs: 48, fat: 10, sodium: 420 },
    ingredients: ["닭가슴살", "불린쌀", "당근", "애호박"],
    steps: ["닭고기를 볶아 향을 냅니다.", "쌀과 채소를 넣고 죽처럼 끓입니다."],
    tip: "자극이 적어 아침 식사로 부담이 적습니다."
  },
  {
    id: "b15",
    title: "낫또 현미 덮밥",
    mealType: "breakfast",
    cuisine: "japanese",
    dietary: ["vegetarian"],
    allergens: ["soy"],
    goals: ["liver", "general", "study"],
    situations: ["office", "student"],
    proteinGroup: "plant",
    prepTime: 7,
    nutrition: { calories: 355, protein: 18, carbs: 49, fat: 9, sodium: 330 },
    ingredients: ["낫또", "현미밥", "김", "쪽파", "간장 소량"],
    steps: ["밥 위에 낫또와 김, 쪽파를 올립니다.", "간장은 최소량으로 조절합니다."],
    tip: "장 건강 관리 식단으로 활용됩니다."
  },

  {
    id: "l01",
    title: "닭가슴살 비빔밥",
    mealType: "lunch",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["soy"],
    goals: ["diet", "muscle", "general"],
    situations: ["office", "workout"],
    proteinGroup: "chicken",
    prepTime: 20,
    nutrition: { calories: 560, protein: 37, carbs: 62, fat: 16, sodium: 640 },
    ingredients: ["현미밥", "닭가슴살", "시금치", "콩나물", "저염고추장"],
    steps: ["채소를 데치고 닭가슴살을 구워 준비합니다.", "밥 위에 올려 비벼 먹습니다."],
    tip: "양념은 반 스푼씩 단계적으로 넣어 조절하세요."
  },
  {
    id: "l02",
    title: "연어 포케볼",
    mealType: "lunch",
    cuisine: "japanese",
    dietary: ["pescatarian"],
    allergens: ["seafood", "soy"],
    goals: ["study", "general", "muscle"],
    situations: ["student", "workout"],
    proteinGroup: "seafood",
    prepTime: 16,
    nutrition: { calories: 590, protein: 34, carbs: 58, fat: 22, sodium: 520 },
    ingredients: ["연어", "현미밥", "아보카도", "오이", "간장 소량"],
    steps: ["재료를 큐브로 썰어 볼에 담습니다.", "소스를 가볍게 버무립니다."],
    tip: "점심 집중력 저하를 줄이는 식단입니다."
  },
  {
    id: "l03",
    title: "소불고기 퀴노아볼",
    mealType: "lunch",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["soy"],
    goals: ["muscle", "general"],
    situations: ["workout", "office"],
    proteinGroup: "beef",
    prepTime: 24,
    nutrition: { calories: 640, protein: 39, carbs: 55, fat: 28, sodium: 760 },
    ingredients: ["우둔살", "퀴노아", "양파", "파프리카", "저염간장"],
    steps: ["소고기를 볶아 양파와 함께 익힙니다.", "퀴노아와 채소를 함께 담습니다."],
    tip: "운동일 에너지 보강용 점심으로 사용하세요."
  },
  {
    id: "l04",
    title: "두부 메밀 샐러드",
    mealType: "lunch",
    cuisine: "japanese",
    dietary: ["vegetarian"],
    allergens: ["soy", "wheat"],
    goals: ["diet", "liver", "general"],
    situations: ["office", "busy"],
    proteinGroup: "plant",
    prepTime: 18,
    nutrition: { calories: 490, protein: 23, carbs: 60, fat: 15, sodium: 430 },
    ingredients: ["메밀면", "두부", "오이", "양배추", "참깨드레싱"],
    steps: ["메밀면을 삶아 식힙니다.", "두부와 채소를 넣고 드레싱을 곁들입니다."],
    tip: "점심 졸림이 심할 때 가벼운 탄단 구성입니다."
  },
  {
    id: "l05",
    title: "병아리콩 퀴노아 샐러드",
    mealType: "lunch",
    cuisine: "mediterranean",
    dietary: ["vegetarian"],
    allergens: [],
    goals: ["diet", "study", "general"],
    situations: ["office", "student"],
    proteinGroup: "plant",
    prepTime: 14,
    nutrition: { calories: 480, protein: 19, carbs: 61, fat: 16, sodium: 360 },
    ingredients: ["병아리콩", "퀴노아", "오이", "토마토", "올리브오일"],
    steps: ["퀴노아를 삶아 식힙니다.", "채소와 콩을 섞어 오일로 버무립니다."],
    tip: "채식 기반 점심의 기본 메뉴입니다."
  },
  {
    id: "l06",
    title: "새우 현미볶음밥",
    mealType: "lunch",
    cuisine: "chinese",
    dietary: ["pescatarian"],
    allergens: ["shellfish", "seafood", "egg", "soy"],
    goals: ["muscle", "general", "study"],
    situations: ["busy", "office"],
    proteinGroup: "seafood",
    prepTime: 17,
    nutrition: { calories: 570, protein: 33, carbs: 64, fat: 18, sodium: 690 },
    ingredients: ["새우", "현미밥", "달걀", "완두콩", "간장"],
    steps: ["새우와 채소를 볶습니다.", "밥과 달걀을 넣고 빠르게 마무리합니다."],
    tip: "나트륨이 높아지지 않게 간장 양을 줄이세요."
  },
  {
    id: "l07",
    title: "칠면조 통밀샌드",
    mealType: "lunch",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: ["wheat"],
    goals: ["diet", "general", "study"],
    situations: ["busy", "office"],
    proteinGroup: "turkey",
    prepTime: 10,
    nutrition: { calories: 510, protein: 34, carbs: 47, fat: 18, sodium: 620 },
    ingredients: ["통밀빵", "칠면조 슬라이스", "토마토", "양상추", "머스터드"],
    steps: ["빵 사이에 재료를 층층이 넣습니다.", "반으로 잘라 간편하게 섭취합니다."],
    tip: "이동 중 점심 대체에 적합합니다."
  },
  {
    id: "l08",
    title: "고등어 구이 정식",
    mealType: "lunch",
    cuisine: "korean",
    dietary: ["pescatarian"],
    allergens: ["seafood"],
    goals: ["study", "general", "liver"],
    situations: ["office", "student"],
    proteinGroup: "seafood",
    prepTime: 22,
    nutrition: { calories: 610, protein: 35, carbs: 58, fat: 24, sodium: 640 },
    ingredients: ["고등어", "보리밥", "쌈채소", "된장국"],
    steps: ["고등어를 노릇하게 구워 준비합니다.", "밥과 채소를 함께 제공합니다."],
    tip: "간장 대신 레몬즙을 활용하면 나트륨을 줄일 수 있습니다."
  },
  {
    id: "l09",
    title: "렌틸콩 카레라이스",
    mealType: "lunch",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: [],
    goals: ["general", "study", "liver"],
    situations: ["student", "night"],
    proteinGroup: "plant",
    prepTime: 25,
    nutrition: { calories: 590, protein: 22, carbs: 82, fat: 16, sodium: 540 },
    ingredients: ["렌틸콩", "현미밥", "양파", "당근", "카레가루"],
    steps: ["렌틸콩과 채소를 카레로 끓입니다.", "현미밥 위에 올려 제공합니다."],
    tip: "포만감이 오래가는 점심입니다."
  },
  {
    id: "l10",
    title: "닭가슴살 토마토 파스타",
    mealType: "lunch",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: ["wheat"],
    goals: ["muscle", "general"],
    situations: ["workout", "office"],
    proteinGroup: "chicken",
    prepTime: 21,
    nutrition: { calories: 630, protein: 42, carbs: 70, fat: 18, sodium: 650 },
    ingredients: ["통밀 파스타", "닭가슴살", "토마토소스", "양파", "마늘"],
    steps: ["파스타를 삶고 닭가슴살을 굽습니다.", "토마토소스와 함께 볶아 완성합니다."],
    tip: "운동 전후 식사로 활용 가능합니다."
  },
  {
    id: "l11",
    title: "두부 버섯 리소토",
    mealType: "lunch",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["dairy", "soy"],
    goals: ["general", "liver"],
    situations: ["night", "office"],
    proteinGroup: "plant",
    prepTime: 27,
    nutrition: { calories: 560, protein: 24, carbs: 66, fat: 20, sodium: 520 },
    ingredients: ["현미리조또쌀", "두부", "버섯", "파르메산", "양파"],
    steps: ["양파와 버섯을 볶아 향을 냅니다.", "쌀과 육수를 넣고 저어가며 익힙니다."],
    tip: "치즈 양을 줄이면 지방과 나트륨을 낮출 수 있습니다."
  },
  {
    id: "l12",
    title: "참치 아보카도 랩",
    mealType: "lunch",
    cuisine: "western",
    dietary: ["pescatarian"],
    allergens: ["wheat", "seafood", "egg"],
    goals: ["study", "general", "diet"],
    situations: ["busy", "office", "student"],
    proteinGroup: "seafood",
    prepTime: 10,
    nutrition: { calories: 520, protein: 31, carbs: 45, fat: 23, sodium: 560 },
    ingredients: ["통밀 또띠아", "참치", "아보카도", "양상추", "요거트소스"],
    steps: ["참치와 소스를 섞습니다.", "또띠아에 채소와 함께 말아줍니다."],
    tip: "손쉽게 휴대 가능한 점심 메뉴입니다."
  },
  {
    id: "l13",
    title: "돼지안심 채소덮밥",
    mealType: "lunch",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["pork", "soy"],
    goals: ["general", "muscle"],
    situations: ["office", "busy"],
    proteinGroup: "pork",
    prepTime: 20,
    nutrition: { calories: 610, protein: 36, carbs: 64, fat: 20, sodium: 710 },
    ingredients: ["돼지안심", "현미밥", "양배추", "파프리카", "간장"],
    steps: ["돼지안심을 센불에 볶습니다.", "채소와 함께 덮밥 형태로 담습니다."],
    tip: "기름을 최소화해 조리하세요."
  },
  {
    id: "l14",
    title: "대구 허브 포테이토 플레이트",
    mealType: "lunch",
    cuisine: "mediterranean",
    dietary: ["pescatarian"],
    allergens: ["seafood"],
    goals: ["liver", "general", "study"],
    situations: ["office", "night"],
    proteinGroup: "seafood",
    prepTime: 24,
    nutrition: { calories: 540, protein: 34, carbs: 52, fat: 18, sodium: 460 },
    ingredients: ["대구살", "감자", "브로콜리", "올리브오일", "허브"],
    steps: ["대구와 감자를 오븐에 굽습니다.", "브로콜리를 곁들여 완성합니다."],
    tip: "저염 점심 구성에 적합합니다."
  },
  {
    id: "l15",
    title: "닭고기 메밀 온국수",
    mealType: "lunch",
    cuisine: "japanese",
    dietary: ["omnivore"],
    allergens: ["wheat", "soy"],
    goals: ["liver", "general", "study"],
    situations: ["night", "office"],
    proteinGroup: "chicken",
    prepTime: 23,
    nutrition: { calories: 560, protein: 33, carbs: 65, fat: 14, sodium: 620 },
    ingredients: ["메밀면", "닭가슴살", "대파", "표고버섯", "저염쯔유"],
    steps: ["닭가슴살과 버섯으로 육수를 냅니다.", "메밀면을 넣고 완성합니다."],
    tip: "국물은 절반만 섭취하면 나트륨 관리에 유리합니다."
  },

  {
    id: "d01",
    title: "연어 스테이크 구운채소",
    mealType: "dinner",
    cuisine: "mediterranean",
    dietary: ["pescatarian"],
    allergens: ["seafood"],
    goals: ["liver", "study", "general"],
    situations: ["night", "office"],
    proteinGroup: "seafood",
    prepTime: 22,
    nutrition: { calories: 540, protein: 36, carbs: 28, fat: 31, sodium: 380 },
    ingredients: ["연어 160g", "브로콜리", "파프리카", "올리브오일", "레몬"],
    steps: ["연어를 팬에 굽습니다.", "채소를 함께 구워 곁들입니다."],
    tip: "늦은 저녁에는 탄수화물 양을 줄여 조절하세요."
  },
  {
    id: "d02",
    title: "두부버섯 전골",
    mealType: "dinner",
    cuisine: "korean",
    dietary: ["vegetarian"],
    allergens: ["soy"],
    goals: ["diet", "liver", "general"],
    situations: ["night", "busy"],
    proteinGroup: "plant",
    prepTime: 24,
    nutrition: { calories: 420, protein: 27, carbs: 34, fat: 18, sodium: 540 },
    ingredients: ["두부", "표고버섯", "청경채", "무", "육수"],
    steps: ["육수와 무를 먼저 끓입니다.", "두부와 버섯, 채소를 넣어 마무리합니다."],
    tip: "저녁 과식을 줄이는 고단백 메뉴입니다."
  },
  {
    id: "d03",
    title: "닭가슴살 채소스튜",
    mealType: "dinner",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: [],
    goals: ["diet", "general", "liver"],
    situations: ["night", "office"],
    proteinGroup: "chicken",
    prepTime: 27,
    nutrition: { calories: 500, protein: 38, carbs: 36, fat: 20, sodium: 460 },
    ingredients: ["닭가슴살", "토마토", "샐러리", "양파", "당근"],
    steps: ["닭가슴살을 먼저 굽습니다.", "채소와 토마토를 넣고 뭉근히 끓입니다."],
    tip: "빵 대신 삶은 감자를 소량 곁들이면 포만감이 좋아집니다."
  },
  {
    id: "d04",
    title: "소고기 채소볶음",
    mealType: "dinner",
    cuisine: "chinese",
    dietary: ["omnivore"],
    allergens: ["soy"],
    goals: ["muscle", "general"],
    situations: ["workout", "busy"],
    proteinGroup: "beef",
    prepTime: 18,
    nutrition: { calories: 590, protein: 39, carbs: 34, fat: 30, sodium: 690 },
    ingredients: ["우둔살", "브로콜리", "양파", "마늘", "간장"],
    steps: ["소고기를 센불에 빠르게 볶습니다.", "채소와 함께 마무리합니다."],
    tip: "근력운동일 저녁에 활용하세요."
  },
  {
    id: "d05",
    title: "새우 브로콜리 마늘볶음",
    mealType: "dinner",
    cuisine: "chinese",
    dietary: ["pescatarian"],
    allergens: ["shellfish", "seafood", "soy"],
    goals: ["diet", "study", "general"],
    situations: ["busy", "office"],
    proteinGroup: "seafood",
    prepTime: 14,
    nutrition: { calories: 390, protein: 32, carbs: 24, fat: 16, sodium: 520 },
    ingredients: ["새우", "브로콜리", "마늘", "올리브오일", "저염간장"],
    steps: ["마늘 향을 내고 새우를 익힙니다.", "브로콜리를 넣고 빠르게 볶습니다."],
    tip: "야근일 15분 완성 저녁으로 적합합니다."
  },
  {
    id: "d06",
    title: "대구 미소국 정식",
    mealType: "dinner",
    cuisine: "japanese",
    dietary: ["pescatarian"],
    allergens: ["seafood", "soy"],
    goals: ["liver", "general"],
    situations: ["night", "office"],
    proteinGroup: "seafood",
    prepTime: 21,
    nutrition: { calories: 480, protein: 33, carbs: 42, fat: 18, sodium: 610 },
    ingredients: ["대구살", "미소", "두부", "미역", "밥 소량"],
    steps: ["육수에 대구와 두부를 넣고 끓입니다.", "미소를 마지막에 풀어 마무리합니다."],
    tip: "미소 양을 줄이면 나트륨을 더 낮출 수 있습니다."
  },
  {
    id: "d07",
    title: "칠면조 미트볼 토마토스튜",
    mealType: "dinner",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: ["egg"],
    goals: ["muscle", "general"],
    situations: ["workout", "office"],
    proteinGroup: "turkey",
    prepTime: 28,
    nutrition: { calories: 610, protein: 42, carbs: 35, fat: 30, sodium: 700 },
    ingredients: ["칠면조 다짐육", "달걀", "토마토소스", "양파", "허브"],
    steps: ["미트볼을 먼저 굽습니다.", "토마토소스에 넣고 끓여 완성합니다."],
    tip: "밥 대신 구운 채소와 함께 먹으면 균형이 좋습니다."
  },
  {
    id: "d08",
    title: "치킨 라이트 카레",
    mealType: "dinner",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: [],
    goals: ["general", "study", "muscle"],
    situations: ["night", "busy"],
    proteinGroup: "chicken",
    prepTime: 25,
    nutrition: { calories: 560, protein: 35, carbs: 54, fat: 22, sodium: 580 },
    ingredients: ["닭가슴살", "감자", "당근", "양파", "카레"],
    steps: ["채소를 볶고 닭가슴살을 넣습니다.", "물과 카레를 넣어 끓입니다."],
    tip: "밥량을 줄이면 감량식으로도 가능합니다."
  },
  {
    id: "d09",
    title: "두부 김치찌개 저염버전",
    mealType: "dinner",
    cuisine: "korean",
    dietary: ["vegetarian"],
    allergens: ["soy"],
    goals: ["liver", "general"],
    situations: ["night", "office"],
    proteinGroup: "plant",
    prepTime: 20,
    nutrition: { calories: 450, protein: 26, carbs: 36, fat: 20, sodium: 640 },
    ingredients: ["두부", "저염 김치", "양파", "대파", "버섯"],
    steps: ["김치를 충분히 씻어 나트륨을 줄입니다.", "두부와 채소를 넣고 끓입니다."],
    tip: "국물 섭취량을 줄이면 나트륨 관리에 좋습니다."
  },
  {
    id: "d10",
    title: "렌틸 채소수프",
    mealType: "dinner",
    cuisine: "mediterranean",
    dietary: ["vegetarian"],
    allergens: [],
    goals: ["diet", "liver", "general"],
    situations: ["night", "student"],
    proteinGroup: "plant",
    prepTime: 26,
    nutrition: { calories: 430, protein: 22, carbs: 56, fat: 12, sodium: 420 },
    ingredients: ["렌틸콩", "샐러리", "당근", "양파", "토마토"],
    steps: ["채소를 볶은 뒤 렌틸콩을 넣고 끓입니다.", "걸쭉해지면 완성합니다."],
    tip: "야식 욕구를 줄이는 따뜻한 저녁 메뉴입니다."
  },
  {
    id: "d11",
    title: "돼지안심 양배추볶음",
    mealType: "dinner",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["pork", "soy"],
    goals: ["muscle", "general"],
    situations: ["busy", "workout"],
    proteinGroup: "pork",
    prepTime: 19,
    nutrition: { calories: 570, protein: 38, carbs: 30, fat: 29, sodium: 700 },
    ingredients: ["돼지안심", "양배추", "양파", "마늘", "간장"],
    steps: ["돼지안심을 볶아 익힙니다.", "양배추를 넣고 빠르게 마무리합니다."],
    tip: "기름 사용량을 줄이면 지방을 낮출 수 있습니다."
  },
  {
    id: "d12",
    title: "고등어구이 보리밥",
    mealType: "dinner",
    cuisine: "korean",
    dietary: ["pescatarian"],
    allergens: ["seafood"],
    goals: ["general", "study", "liver"],
    situations: ["office", "night"],
    proteinGroup: "seafood",
    prepTime: 20,
    nutrition: { calories: 560, protein: 34, carbs: 52, fat: 23, sodium: 530 },
    ingredients: ["고등어", "보리밥", "상추", "레몬"],
    steps: ["고등어를 굽고 보리밥을 준비합니다.", "채소와 함께 제공합니다."],
    tip: "생선은 주 2~3회 반복해도 좋은 단백질원입니다."
  },
  {
    id: "d13",
    title: "참치 스테이크 샐러드",
    mealType: "dinner",
    cuisine: "mediterranean",
    dietary: ["pescatarian"],
    allergens: ["seafood"],
    goals: ["diet", "study", "general"],
    situations: ["night", "busy"],
    proteinGroup: "seafood",
    prepTime: 18,
    nutrition: { calories: 500, protein: 39, carbs: 21, fat: 24, sodium: 430 },
    ingredients: ["참치 스테이크", "샐러드채소", "올리브", "토마토", "올리브오일"],
    steps: ["참치를 겉면만 구워 슬라이스합니다.", "샐러드 위에 올려 드레싱합니다."],
    tip: "탄수화물이 필요하면 통곡물빵 소량을 곁들이세요."
  },
  {
    id: "d14",
    title: "순두부 달걀국",
    mealType: "dinner",
    cuisine: "korean",
    dietary: ["omnivore"],
    allergens: ["soy", "egg"],
    goals: ["liver", "general", "study"],
    situations: ["night", "office"],
    proteinGroup: "egg",
    prepTime: 16,
    nutrition: { calories: 410, protein: 28, carbs: 26, fat: 19, sodium: 520 },
    ingredients: ["순두부", "달걀", "대파", "표고버섯", "육수"],
    steps: ["육수를 끓이고 순두부를 넣습니다.", "달걀물을 풀어 마무리합니다."],
    tip: "야근 후 가볍게 먹기 좋은 메뉴입니다."
  },
  {
    id: "d15",
    title: "치킨 퀴노아 웜샐러드",
    mealType: "dinner",
    cuisine: "western",
    dietary: ["omnivore"],
    allergens: [],
    goals: ["diet", "muscle", "general"],
    situations: ["workout", "office"],
    proteinGroup: "chicken",
    prepTime: 21,
    nutrition: { calories: 530, protein: 37, carbs: 42, fat: 21, sodium: 460 },
    ingredients: ["닭가슴살", "퀴노아", "케일", "방울토마토", "발사믹"],
    steps: ["닭가슴살을 구워 슬라이스합니다.", "퀴노아와 채소를 따뜻하게 섞습니다."],
    tip: "운동일 저녁의 탄단 균형 식단입니다."
  },
  {
    id: "d16",
    title: "두부 채소 데리야키볶음",
    mealType: "dinner",
    cuisine: "japanese",
    dietary: ["vegetarian"],
    allergens: ["soy"],
    goals: ["general", "diet", "liver"],
    situations: ["busy", "night"],
    proteinGroup: "plant",
    prepTime: 17,
    nutrition: { calories: 460, protein: 27, carbs: 38, fat: 19, sodium: 580 },
    ingredients: ["두부", "브로콜리", "표고버섯", "당근", "저염 데리야키소스"],
    steps: ["두부를 굽고 채소를 볶습니다.", "저염 소스를 넣어 짧게 마무리합니다."],
    tip: "야채 비율을 높이면 포만감이 커집니다."
  },
  {
    id: "d17",
    title: "버섯 보리 리소토",
    mealType: "dinner",
    cuisine: "western",
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    goals: ["general", "study", "liver"],
    situations: ["office", "night"],
    proteinGroup: "plant",
    prepTime: 28,
    nutrition: { calories: 500, protein: 19, carbs: 67, fat: 17, sodium: 470 },
    ingredients: ["보리쌀", "양송이", "양파", "파르메산 소량", "채소육수"],
    steps: ["버섯과 양파를 볶습니다.", "보리쌀과 육수를 넣고 저어가며 익힙니다."],
    tip: "치즈를 소량만 사용하면 지방과 나트륨을 줄일 수 있습니다."
  },
  {
    id: "d18",
    title: "병아리콩 토마토 스튜",
    mealType: "dinner",
    cuisine: "mediterranean",
    dietary: ["vegetarian"],
    allergens: [],
    goals: ["diet", "general", "liver"],
    situations: ["night", "student"],
    proteinGroup: "plant",
    prepTime: 24,
    nutrition: { calories: 470, protein: 21, carbs: 61, fat: 14, sodium: 430 },
    ingredients: ["병아리콩", "토마토", "주키니", "양파", "올리브오일"],
    steps: ["채소를 볶은 후 토마토와 콩을 넣고 끓입니다.", "걸쭉해지면 불을 끄고 마무리합니다."],
    tip: "통밀빵 소량을 곁들이면 한 끼 식사로 충분합니다."
  }
];

window.VITAL_DATA = {
  allergyOptions,
  goalProfiles,
  situationGuides,
  recipeCatalog
};
